version: '3'

services:
  sql:
    build:
        context: ./azure-sql
        dockerfile: Dockerfile
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sql
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=123456789Q
      - MSSQL_PID=Developer
      - MSSQL_USER=SA
    ports:
      - "1433:1433"
    restart: always